// SPDX-FileCopyrightText: Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0

//! systemd generator mode (SPEC.md "systemd Integration").
//!
//! When the binary is invoked as `systemd-carapace-generator` (a symlink the
//! dracut module installs into `/usr/lib/systemd/system-generators/`), systemd
//! runs it early with three output directories and expects unit files, not the
//! normal CLI. This module emits a `carapace-attach.service` that assembles the
//! root carapace into `/dev/mapper/root` before `initrd-root-device.target`,
//! reading the trust anchor from `carapacehash=` on the kernel command line.
//! Everything above `/dev/mapper/root` is stock systemd (mount if it holds a
//! filesystem, `systemd-dissect`/`gpt-auto` if it holds a GPT).

use std::fs;
use std::os::unix::fs::symlink;
use std::path::Path;
use std::process::ExitCode;

/// The name systemd invokes us under (the generator symlink's basename).
const GENERATOR_NAME: &str = "systemd-carapace-generator";
/// The unit we emit.
const SERVICE: &str = "carapace-attach.service";
/// The dm name / mount contract: `root=/dev/mapper/root`.
const DEV_NAME: &str = "root";
/// Where the `carapace` binary lands in the initrd (dracut `inst`).
const CARAPACE_BIN: &str = "/usr/bin/carapace";

/// True when `argv[0]`'s basename is the generator symlink name.
pub(crate) fn invoked_as_generator(arg0: &str) -> bool {
    Path::new(arg0).file_name().and_then(|s| s.to_str()) == Some(GENERATOR_NAME)
}

/// Generator entry point. systemd passes `argv[1..=3]` = normal/early/late
/// output dirs; we write to the normal dir (`argv[1]`).
pub(crate) fn run() -> ExitCode {
    let Some(normal_dir) = std::env::args().nth(1) else {
        eprintln!("carapace generator: missing output directory argument");
        return ExitCode::FAILURE;
    };
    let cmdline = match fs::read_to_string("/proc/cmdline") {
        Ok(c) => c,
        Err(e) => {
            eprintln!("carapace generator: read /proc/cmdline: {e}");
            return ExitCode::FAILURE;
        }
    };
    match generate(Path::new(&normal_dir), &cmdline) {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("carapace generator: {e}");
            ExitCode::FAILURE
        }
    }
}

/// Emit the unit into `dir` if the command line asks for a carapace root.
/// A missing `carapacehash=` (or `systemd.carapace=no`) is a no-op, not an
/// error — the image may boot its root some other way.
fn generate(dir: &Path, cmdline: &str) -> Result<(), String> {
    if !enabled(cmdline) {
        return Ok(());
    }
    let Some(hash) = carapace_hash(cmdline) else {
        return Ok(());
    };
    if !is_lower_hex(hash) || hash.len() < 64 {
        return Err(format!(
            "carapacehash= must be lowercase hex of at least 64 chars, got {hash:?}"
        ));
    }

    fs::write(dir.join(SERVICE), unit_text(hash)).map_err(|e| format!("write {SERVICE}: {e}"))?;

    // Pull the unit into the root-device transaction and order it before the
    // root device is required. A failed assembly then fails the boot closed.
    let reqs = dir.join("initrd-root-device.target.requires");
    fs::create_dir_all(&reqs).map_err(|e| format!("create {}: {e}", reqs.display()))?;
    match symlink(format!("../{SERVICE}"), reqs.join(SERVICE)) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => Ok(()),
        Err(e) => Err(format!("symlink {SERVICE} into {}: {e}", reqs.display())),
    }
}

/// The `carapace-attach.service` text. The hash is baked in (the generator
/// already parsed and validated it), so `attach` needs no cmdline access.
fn unit_text(hash: &str) -> String {
    format!(
        "# Automatically generated by {GENERATOR_NAME}\n\
         [Unit]\n\
         Description=Assemble the root carapace\n\
         DefaultDependencies=no\n\
         Before=initrd-root-device.target\n\
         ConditionPathExists=/dev/mapper/control\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         RemainAfterExit=yes\n\
         ExecStart={CARAPACE_BIN} attach --name {DEV_NAME} --root {hash}\n"
    )
}

/// `systemd.carapace=` / `rd.systemd.carapace=` master switch (default on).
/// Only an explicit `no`/`0`/`false` disables the generator.
fn enabled(cmdline: &str) -> bool {
    for tok in cmdline.split_whitespace() {
        let v = tok
            .strip_prefix("rd.systemd.carapace=")
            .or_else(|| tok.strip_prefix("systemd.carapace="));
        if let Some(v) = v {
            return !matches!(v, "no" | "0" | "false" | "off");
        }
    }
    true
}

/// The trust anchor: `carapacehash=<hex>`, with `root.carapace=` accepted as a
/// transitional alias. Last occurrence wins (systemd cmdline convention).
fn carapace_hash(cmdline: &str) -> Option<&str> {
    let mut found = None;
    for tok in cmdline.split_whitespace() {
        if let Some(v) = tok
            .strip_prefix("carapacehash=")
            .or_else(|| tok.strip_prefix("root.carapace="))
        {
            if !v.is_empty() {
                found = Some(v);
            }
        }
    }
    found
}

fn is_lower_hex(s: &str) -> bool {
    !s.is_empty()
        && s.bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}

#[cfg(test)]
mod tests {
    use super::*;

    const H: &str = "aa11bb22cc33dd44ee55ff66aa77bb88cc99dd00ee11ff22aa33bb44cc55dd66";

    #[test]
    fn hash_and_alias_and_last_wins() {
        assert_eq!(
            carapace_hash(&format!("console=hvc0 carapacehash={H} ro")),
            Some(H)
        );
        assert_eq!(carapace_hash(&format!("root.carapace={H}")), Some(H)); // alias
                                                                           // last occurrence wins
        assert_eq!(
            carapace_hash("carapacehash=dead root.carapace=beef"),
            Some("beef")
        );
        assert_eq!(carapace_hash("console=hvc0"), None);
        assert_eq!(carapace_hash("carapacehash="), None);
    }

    #[test]
    fn switch_defaults_on_and_respects_off() {
        assert!(enabled("console=hvc0"));
        assert!(enabled("systemd.carapace=yes"));
        assert!(!enabled("systemd.carapace=no"));
        assert!(!enabled("rd.systemd.carapace=0"));
        assert!(!enabled("systemd.carapace=false"));
    }

    #[test]
    fn unit_bakes_hash_and_ordering() {
        let u = unit_text(H);
        assert!(u.contains(&format!("--root {H}")));
        assert!(u.contains("--name root"));
        assert!(u.contains("Before=initrd-root-device.target"));
        assert!(u.contains("Type=oneshot"));
    }

    #[test]
    fn generate_writes_unit_and_symlink() {
        let tmp = std::env::temp_dir().join(format!("carapace-gen-test-{}", std::process::id()));
        let _ = fs::remove_dir_all(&tmp);
        fs::create_dir_all(&tmp).unwrap();

        generate(
            &tmp,
            &format!("console=hvc0 carapacehash={H} root=/dev/mapper/root"),
        )
        .unwrap();
        assert!(tmp.join(SERVICE).is_file(), "service written");
        let link = tmp.join("initrd-root-device.target.requires").join(SERVICE);
        assert!(
            fs::symlink_metadata(&link).is_ok(),
            "requires symlink written"
        );

        // No hash → no-op.
        let tmp2 = tmp.join("empty");
        fs::create_dir_all(&tmp2).unwrap();
        generate(&tmp2, "console=hvc0").unwrap();
        assert!(
            !tmp2.join(SERVICE).exists(),
            "no unit without carapacehash="
        );

        let _ = fs::remove_dir_all(&tmp);
    }

    #[test]
    fn disabled_switch_is_noop() {
        let tmp = std::env::temp_dir().join(format!("carapace-gen-off-{}", std::process::id()));
        let _ = fs::remove_dir_all(&tmp);
        fs::create_dir_all(&tmp).unwrap();
        generate(&tmp, &format!("carapacehash={H} systemd.carapace=no")).unwrap();
        assert!(!tmp.join(SERVICE).exists());
        let _ = fs::remove_dir_all(&tmp);
    }

    #[test]
    fn generator_name_dispatch() {
        assert!(invoked_as_generator(
            "/usr/lib/systemd/system-generators/systemd-carapace-generator"
        ));
        assert!(invoked_as_generator("systemd-carapace-generator"));
        assert!(!invoked_as_generator("/usr/bin/carapace"));
        assert!(!invoked_as_generator("carapace"));
    }
}
